hapi:
    port: 8080

database:
  type: postgres
  host: localhost
  port: 5433
  username: sevenmiles
  password: Passw0rd!
  database: sevenmiles
  synchronize: true
  logging: true

logging:
  level: debug
