import { Request, ResponseToolkit } from "@hapi/hapi";
import { inject, injectable } from "inversify";
import { TYPES } from "../ioc/types";
import { Logger } from "winston";
import { HapiRoute } from "../decorators/decorators";
import { HapiController } from "./hapi-controller";
import * as Joi from '@hapi/joi';
import * as Boom from "@hapi/boom";
import { Mapper } from "../helpers/mapper";
import { ITeamController } from './interfaces/team.interface';

import { TeamService } from '../service/team.service';
// import { TeamModel } from '../dto/team';
// import { Team } from '../entity/team';

/**
 * This file is automatically generated by swagger.  This is a stub.  It is expected that developers will fill in the logic
 * for each method - as generated each endpoint will return a 501 - not implemented.
 *
 * IT IS NOT SAFE TO OVERWRITE AN EXISTING FILE WITH THIS ONE.
 *
 * If there are changes to the swagger that describes routes implemented in this controller, the related interface will
 * change and the TypeScript compiler will complain that the controller does not implement the interface correctly.  In
 * this case, you can find the missing (added) method(s) in the generated controller and copy the stubs to your implementation.
 */
@injectable()
class TeamController extends HapiController implements ITeamController {

  /**
   * Here we are also injecting the car service to manage interactions with the database
   * in addition to the logger and mapper.  You can inject as many dependencies as you need.
   *
   * This is a test.
   */
  constructor(
      @inject(TYPES.Logger) private logger: Logger,
      @inject(TYPES.TeamService) private teamService: TeamService,
      @inject(TYPES.Mapper) private mapper: Mapper)
  {
      super();
      this.logger.info('Created controller TeamController');
  }

/**
 * Add a new team to the system
 */
  @HapiRoute({
    method: 'POST',
    path: 'teams',
    options: {
      validate: { },
      description: 'Add a new team to the system',
      tags: ['team',],
      auth: false
    }
  })
  public async addTeam(request: Request, toolkit: ResponseToolkit) {
    return toolkit.response().code(501);
  }

/**
 * Finds all the teams
 */
  @HapiRoute({
    method: 'GET',
    path: 'teams',
    options: {
      validate: { },
      description: 'Finds Teams',
      tags: ['team',],
      auth: false
    }
  })
  public async findTeams(request: Request, toolkit: ResponseToolkit) {
    return toolkit.response().code(501);
  }

/**
 * Returns a single team
 */
  @HapiRoute({
    method: 'GET',
    path: 'teams/{id}',
    options: {
      validate: { },
      description: 'Find team by ID',
      tags: ['team',],
      auth: false
    }
  })
  public async getTeamById(request: Request, toolkit: ResponseToolkit) {
    return toolkit.response().code(501);
  }

/**
 * Updates an existing team by ID
 */
  @HapiRoute({
    method: 'PATCH',
    path: 'teams/{id}',
    options: {
      validate: { },
      description: 'Updates an existing team by ID',
      tags: ['team',],
      auth: false
    }
  })
  public async updateTeam(request: Request, toolkit: ResponseToolkit) {
    return toolkit.response().code(501);
  }

/**
 * Deletes a team by ID
 */
  @HapiRoute({
    method: 'DELETE',
    path: 'teams/{id}',
    options: {
      validate: { },
      description: 'Deletes a team by ID',
      tags: ['team',],
      auth: false
    }
  })
  public async deleteTeam(request: Request, toolkit: ResponseToolkit) {
    return toolkit.response().code(501);
  }

}

export { TeamController }
