import { Request, ResponseToolkit } from '@hapi/hapi'

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the AddressController must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface IAddressController {



  /**
  * Add a new address to the system
  */
  public async addAddress(request: Request, toolkit: ResponseToolkit)

  /**
  * Finds all the addresses
  */
  public async findAddresses(request: Request, toolkit: ResponseToolkit)

  /**
  * Returns a single address
  */
  public async getAddressById(request: Request, toolkit: ResponseToolkit)

  /**
  * Updates an existing address by ID
  */
  public async updateAddress(request: Request, toolkit: ResponseToolkit)

  /**
  * Delete an address by ID
  */
  public async deleteAddress(request: Request, toolkit: ResponseToolkit)

}

export { IAddressController }
