import { Request, ResponseToolkit } from '@hapi/hapi'

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the CarController must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface ICarController {



  /**
  * Add a new car to the system
  */
  addCar(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Finds all the cars
  */
  findCars(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Returns a single car
  */
  getCarById(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Updates an existing car by ID
  */
  updateCar(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Deletes a car by ID
  */
  deleteCar(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Get a car's results
  */
  getCarResults(request: Request, toolkit: ResponseToolkit) : Promise<any>

}

export { ICarController }
