import { Request, ResponseToolkit } from '@hapi/hapi'

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the CarController must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface ICarController {



  /**
  * Add a new car to the system
  */
  public async addCar(request: Request, toolkit: ResponseToolkit)

  /**
  * Finds all the cars
  */
  public async findCars(request: Request, toolkit: ResponseToolkit)

  /**
  * Returns a single car
  */
  public async getCarById(request: Request, toolkit: ResponseToolkit)

  /**
  * Updates an existing car by ID
  */
  public async updateCar(request: Request, toolkit: ResponseToolkit)

  /**
  * Deletes a car by ID
  */
  public async deleteCar(request: Request, toolkit: ResponseToolkit)

  /**
  * Get a car's results
  */
  public async getCarResults(request: Request, toolkit: ResponseToolkit)

}

export { ICarController }
