import { Request, ResponseToolkit } from '@hapi/hapi'

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the ClassController must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface IClassController {



  /**
  * Add a new class to the system
  */
  addClass(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Finds all the classes
  */
  findClasses(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Returns a single class
  */
  getClassById(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Updates an existing class by ID
  */
  updateClass(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Deletes a class by ID
  */
  deleteClass(request: Request, toolkit: ResponseToolkit) : Promise<any>

}

export { IClassController }
