import { Request, ResponseToolkit } from "@hapi/hapi";

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the ClassController must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface IClassController {



  /**
  * Add a new class to the system
  */
  public async addClass(request: Request, toolkit: ResponseToolkit);

  /**
  * Finds all the classes
  */
  public async findClasses(request: Request, toolkit: ResponseToolkit);

  /**
  * Returns a single class
  */
  public async getClassById(request: Request, toolkit: ResponseToolkit);

  /**
  * Updates an existing class by ID
  */
  public async updateClass(request: Request, toolkit: ResponseToolkit);

  /**
  * Deletes a class by ID
  */
  public async deleteClass(request: Request, toolkit: ResponseToolkit);

}

export { IClassController }
