import { Request, ResponseToolkit } from '@hapi/hapi'

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the DriverController must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface IDriverController {



  /**
  * Add a new driver to the system
  */
  public async addDriver(request: Request, toolkit: ResponseToolkit)

  /**
  * Finds all the drivers
  */
  public async findDrivers(request: Request, toolkit: ResponseToolkit)

  /**
  * Returns a single driver
  */
  public async getDriverById(request: Request, toolkit: ResponseToolkit)

  /**
  * Updates an existing driver by ID
  */
  public async updateDriver(request: Request, toolkit: ResponseToolkit)

  /**
  * Deletes a driver by ID
  */
  public async deleteDriver(request: Request, toolkit: ResponseToolkit)

  /**
  * Get driver's results on races
  */
  public async getDriverRaceResults(request: Request, toolkit: ResponseToolkit)

}

export { IDriverController }
