import { Request, ResponseToolkit } from '@hapi/hapi'

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the RaceController must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface IRaceController {



  /**
  * Add a new race (with its results) to the system
  */
  addRace(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Finds all the races
  */
  findRaces(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Returns a single race
  */
  getRaceById(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Updates an existing race by ID
  */
  updateRace(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Deletes a race by ID
  */
  deleteRace(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Get a race's results
  */
  getRaceResults(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Add new race results for an existing race
  */
  addRaceResult(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Updates an existing race result
  */
  updateRaceResult(request: Request, toolkit: ResponseToolkit) : Promise<any>

}

export { IRaceController }
