import { Request, ResponseToolkit } from "@hapi/hapi";

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the RaceController must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface IRaceController {



  /**
  * Add a new race (with its results) to the system
  */
  public async addRace(request: Request, toolkit: ResponseToolkit);

  /**
  * Finds all the races
  */
  public async findRaces(request: Request, toolkit: ResponseToolkit);

  /**
  * Returns a single race
  */
  public async getRaceById(request: Request, toolkit: ResponseToolkit);

  /**
  * Updates an existing race by ID
  */
  public async updateRace(request: Request, toolkit: ResponseToolkit);

  /**
  * Deletes a race by ID
  */
  public async deleteRace(request: Request, toolkit: ResponseToolkit);

  /**
  * Get a race's results
  */
  public async getRaceResults(request: Request, toolkit: ResponseToolkit);

  /**
  * Add new race results for an existing race
  */
  public async addRaceResult(request: Request, toolkit: ResponseToolkit);

  /**
  * Updates an existing race result
  */
  public async updateRaceResult(request: Request, toolkit: ResponseToolkit);

}

export { IRaceController }
