import { Request, ResponseToolkit } from '@hapi/hapi'

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the TeamController must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface ITeamController {



  /**
  * Add a new team to the system
  */
  addTeam(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Finds all the teams
  */
  findTeams(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Returns a single team
  */
  getTeamById(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Updates an existing team by ID
  */
  updateTeam(request: Request, toolkit: ResponseToolkit) : Promise<any>

  /**
  * Deletes a team by ID
  */
  deleteTeam(request: Request, toolkit: ResponseToolkit) : Promise<any>

}

export { ITeamController }
